# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7708d4b7fa33769cebae89edcf1f3a6361e8f1c878918c19aea66a8603212b4da42a79928aa39fc33bde9547fecf3f897a579a0e63fd3140ad5535d32c144691

test:
  secret_key_base: af5308a907c90f17ba4a7f22f1861eba3ba858d7823d9c6d66b963defed389f6536fb83f985dfd483f3df2b823c452d4ec78d1724e7841e160cb0eb9167dc899

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
